[package]
name = "protobuf"
version = "0.1.0"
authors = ["Lauri Annala <lauri.annala@solita.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0"
prost = "0.7"

[build-dependencies]
prost-build = "0.7"
